//Localization file
//This defines all of the text that is displayed to the player.
//Simply change the strings at the end of each line and recompile the progs to change what the text is in-game.

#define LOC_EPILOGUE_1 "This is the epilogue text for Episode 1.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."
#define LOC_EPILOGUE_1_FREEWARE "This is the epilogue text for the unregistered Episode 1.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."
#define LOC_EPILOGUE_2 "This is the epilogue text for Episode 2.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."
#define LOC_EPILOGUE_3 "This is the epilogue text for Episode 3.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."
#define LOC_EPILOGUE_4 "This is the epilogue text for Episode 4.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."
#define LOC_EPILOGUE_FINAL "This is the epilogue text that plays\nonce you have collected all four runes.\nReplace it around line 5 of localization.qc.\nUse \\n to denote a new line."

//Note that the leading space is required.
//If you don't include it, there will be no space between the player's name and the rest of the text.
#define LOC_EXIT " exited the level"
#define LOC_SUICIDE " suicides"
#define LOC_PICKUP "You got "
#define LOC_PICKUP_HEALTH "You receive "
#define LOC_BACKPACK " from a backpack"

#define LOC_QUAD_FADE "The Crusher Sigil's power is dwindling"
#define LOC_PENT_FADE "Lucifer's Aegis is almost gone!"
#define LOC_RING_FADE "The Eye of Eryx is fading away"
#define LOC_BIO_FADE "Your Hazmat Suit is about to expire"

#define LOC_NETNAME_QUAD "the Crusher Sigil!"
#define LOC_NETNAME_PENT "Lucifer's Aegis"
#define LOC_NETNAME_RING "The Eye of Eryx"
#define LOC_NETNAME_BIO "the Hazmat Suit"

#define LOC_NETNAME_SHELLS "shells"
#define LOC_NETNAME_NAILS "nails"
#define LOC_NETNAME_ROCKETS "rockets"
#define LOC_NETNAME_CELLS "cells"

#define LOC_DEATH_ARMY 			" was killed by a Foot Soldier"
#define LOC_DEATH_ENFORCER 		" was blasted by a Commando"
#define LOC_DEATH_DOG 			" was bitten by a Rottweiler"
#define LOC_DEATH_OGRE 			" was destroyed by an Ogre"
#define LOC_DEATH_DEMON1 		" was eviscerated by a Fiend"
#define LOC_DEATH_WIZARD 		" was scragged by a Scrag"
#define LOC_DEATH_ZOMBIE		"'s brain was eaten by a Zombie"
#define LOC_DEATH_KNIGHT 		" was slashed by a Knight"
#define LOC_DEATH_HELL_KNIGHT 	" was slain by a Death Knight"
#define LOC_DEATH_FISH 			" was fed to the Rotfish"
#define LOC_DEATH_SHAMBLER 		" was smashed by a Shambler"
#define LOC_DEATH_SHALRATH 		" was exploded by a Vore"
#define LOC_DEATH_TARBABY 		" was slimed by a Spawn"
#define LOC_DEATH_BOSS 			" was fireballed by Cthon"
#define LOC_DEATH_OLDONE 		" became one with Shub-Niggurath"
#define LOC_DEATH_MONSTER		" was slain by some abomnination"

#define LOC_DEATH_EXPLO_BOX 	" exploded"
#define LOC_DEATH_SQUISH 		" was crushed"
#define LOC_DEATH_TRAP_SPIKE	" was shot by a spike turret"
#define LOC_DEATH_TRAP_LASER	" was shot by a laser turret"
#define LOC_DEATH_FIREBALL		" ate a lavaball"
#define LOC_DEATH_LEAVE			" tried to escape the arena"
#define LOC_DEATH_DROWN1		" ran out of air"
#define LOC_DEATH_DROWN2		" drowned"
#define LOC_DEATH_DROWN3		" fell to a watery grave"
#define LOC_DEATH_SLIME1		" shouldn't have played with acid"
#define LOC_DEATH_SLIME2		" was burned by the acid"
#define LOC_DEATH_LAVA1			" combusted"
#define LOC_DEATH_LAVA2			" fell into a volcano"
#define LOC_DEATH_LAVA3			" shouldn't have played with lava"
#define LOC_DEATH_FALL_1		" fell off a cliff"
#define LOC_DEATH_FALL_2		" took a long flight off a short runway"
#define LOC_DEATH_DISCHARGE		" electrocuted himself"
#define LOC_DEATH_SELF_GRENADE	" wasn't careful with explosives"
#define LOC_DEATH_SELF_ROCKET	" blew himself up"
#define LOC_DEATH_SELF_OTHER	" had a death-wish"
#define LOC_DEATH_OTHER			" died"

//Weapon deathstring 2 has a 1/33 chance to be used
#define LOC_DEATH_AXE_1A	" was brutally beaten by "
#define LOC_DEATH_AXE_1B	""
#define LOC_DEATH_AXE_2A	" was savagely beaten by "
#define LOC_DEATH_AXE_2B	""
#define LOC_DEATH_AXE_QA	" was crushed beneath "
#define LOC_DEATH_AXE_QB	"'s Hammer"

#define LOC_DEATH_SHOTGUN_1A	" sucked on "
#define LOC_DEATH_SHOTGUN_1B	"'s muffler"
#define LOC_DEATH_SHOTGUN_2A	" chewed on "
#define LOC_DEATH_SHOTGUN_2B	"'s muffler"
#define LOC_DEATH_SHOTGUN_QA	" was put six feet under by "
#define LOC_DEATH_SHOTGUN_QB	""

#define LOC_DEATH_SUPER_SHOTGUN_1A	" was blasted by "
#define LOC_DEATH_SUPER_SHOTGUN_1B	"'s shotgun"
#define LOC_DEATH_SUPER_SHOTGUN_2A	" was eliminated by "
#define LOC_DEATH_SUPER_SHOTGUN_2B	"'s shotgun"
#define LOC_DEATH_SUPER_SHOTGUN_QA	" was sent home in a box by "
#define LOC_DEATH_SUPER_SHOTGUN_QB	""

#define LOC_DEATH_NAILGUN_1A	" was pierced by "
#define LOC_DEATH_NAILGUN_1B	"'s Machine Gun"
#define LOC_DEATH_NAILGUN_2A	" was perforated by "
#define LOC_DEATH_NAILGUN_2B	"'s Machine Gun"
#define LOC_DEATH_NAILGUN_QA	
#define LOC_DEATH_NAILGUN_QB	

#define LOC_DEATH_SUPER_NAILGUN_1A	" was pierced by "
#define LOC_DEATH_SUPER_NAILGUN_1B	"'s Chaingun"
#define LOC_DEATH_SUPER_NAILGUN_2A	" was perforated by "
#define LOC_DEATH_SUPER_NAILGUN_2B	"'s Chaingun"
#define LOC_DEATH_SUPER_NAILGUN_QA	
#define LOC_DEATH_SUPER_NAILGUN_QB	

#define LOC_DEATH_GRENADE_LAUNCHER_1A	
#define LOC_DEATH_GRENADE_LAUNCHER_1B	
#define LOC_DEATH_GRENADE_LAUNCHER_2A	
#define LOC_DEATH_GRENADE_LAUNCHER_2B	
#define LOC_DEATH_GRENADE_LAUNCHER_GA	
#define LOC_DEATH_GRENADE_LAUNCHER_GB	
#define LOC_DEATH_GRENADE_LAUNCHER_QA	
#define LOC_DEATH_GRENADE_LAUNCHER_QB	

#define LOC_DEATH_ROCKET_LAUNCHER_1A	
#define LOC_DEATH_ROCKET_LAUNCHER_1B	
#define LOC_DEATH_ROCKET_LAUNCHER_2A	
#define LOC_DEATH_ROCKET_LAUNCHER_2B	
#define LOC_DEATH_ROCKET_LAUNCHER_GA	
#define LOC_DEATH_ROCKET_LAUNCHER_GB	
#define LOC_DEATH_ROCKET_LAUNCHER_QA	
#define LOC_DEATH_ROCKET_LAUNCHER_QB	
#define LOC_DEATH_ROCKET_LAUNCHER_PA	" will see "
#define LOC_DEATH_ROCKET_LAUNCHER_PB	" in hell"

#define LOC_DEATH_LIGHTNING_1A	
#define LOC_DEATH_LIGHTNING_1B				
#define LOC_DEATH_LIGHTNING_2A	
#define LOC_DEATH_LIGHTNING_2B	
#define LOC_DEATH_LIGHTNING_QA	
#define LOC_DEATH_LIGHTNING_QB	
#define LOC_DEATH_LIGHTNING_DA	
#define LOC_DEATH_LIGHTNING_DB	

#define LOC_DEATH_TELEFRAG_A	
#define LOC_DEATH_TELEFRAG_B	

#define LOC_DEATH_DEFLECT_A	"'s telefrag on "
#define LOC_DEATH_DEFLECT_B	" was deflected by Lucifer's influence"

#define LOC_TEAMKILL_1	" mows down a teammate"
#define LOC_TEAMKILL_2	" checks his glasses"
#define LOC_TEAMKILL_3	" gets a frag for the other team"
#define LOC_TEAMKILL_4	" loses another friend"

#define LOC_ERR_CHANGELEVEL_NOMAP "changelevel trigger doesn't have map"
#define LOC_ERR_NOSTART "PutClientInServer: no info_player_start on level"








